# Project: Project3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Graphics\ PAS.o"
LINKOBJ  = "Graphics PAS.o"
LIBS     = -L"C:/Users/ZAKARIA AHMED/Desktop/dev/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32 -luser32 -m32
INCS     = -I"C:/Users/ZAKARIA AHMED/Desktop/dev/MinGW64/include" -I"C:/Users/ZAKARIA AHMED/Desktop/dev/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ZAKARIA AHMED/Desktop/dev/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/ZAKARIA AHMED/Desktop/dev/MinGW64/include" -I"C:/Users/ZAKARIA AHMED/Desktop/dev/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ZAKARIA AHMED/Desktop/dev/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/ZAKARIA AHMED/Desktop/dev/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "C++ Submission.exe"
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"Graphics\ PAS.o": Graphics\ PAS.cpp
	$(CPP) -c "Graphics PAS.cpp" -o "Graphics PAS.o" $(CXXFLAGS)
